// Tie class generated by rmic, do not edit.
// Contents subject to change without notice.

package br.smat.transaction.acidentetransaction;

import br.smat.objetosauxiliares.auxtestemunha.AuxTestemunha;
import java.io.Serializable;
import java.rmi.Remote;
import java.rmi.RemoteException;
import javax.ejb.EJBHome;
import javax.ejb.EJBObject;
import javax.ejb.Handle;
import javax.ejb.RemoveException;
import javax.rmi.CORBA.Util;
import org.omg.CORBA.BAD_OPERATION;
import org.omg.CORBA.SystemException;
import org.omg.CORBA.portable.UnknownException;

public class _EJSRemoteStatelessAcidenteTransaction_39fa3a6a_Tie extends org.omg.CORBA_2_3.portable.ObjectImpl implements javax.rmi.CORBA.Tie {
    
    private EJSRemoteStatelessAcidenteTransaction_39fa3a6a target = null;
    private org.omg.CORBA.ORB orb = null;
    
    private static final String[] _type_ids = {
        "RMI:br.smat.transaction.acidentetransaction.AcidenteTransaction:0000000000000000", 
        "RMI:javax.ejb.EJBObject:0000000000000000", 
        "RMI:com.ibm.websphere.csi.CSIServant:0000000000000000", 
        "RMI:com.ibm.websphere.csi.TransactionalObject:0000000000000000"
    };
    
    public void setTarget(java.rmi.Remote target) {
        this.target = (EJSRemoteStatelessAcidenteTransaction_39fa3a6a) target;
    }
    
    public java.rmi.Remote getTarget() {
        return target;
    }
    
    public org.omg.CORBA.Object thisObject() {
        return this;
    }
    
    public void deactivate() {
        if (orb != null) {
            orb.disconnect(this);
            _set_delegate(null);
        }
    }
    
    public org.omg.CORBA.ORB orb() {
        return _orb();
    }
    
    public void orb(org.omg.CORBA.ORB orb) {
        orb.connect(this);
    }
    
    public void _set_delegate(org.omg.CORBA.portable.Delegate del) {
        super._set_delegate(del);
        if (del != null)
            orb = _orb();
        else
            orb = null;
    }
    
    public String[] _ids() { 
        return _type_ids;
    }
    
    public org.omg.CORBA.portable.OutputStream _invoke(String method, org.omg.CORBA.portable.InputStream _in, org.omg.CORBA.portable.ResponseHandler reply) throws org.omg.CORBA.SystemException {
        try {
            org.omg.CORBA_2_3.portable.InputStream in = 
                (org.omg.CORBA_2_3.portable.InputStream) _in;
            switch (method.length()) {
                case 4: 
                    if (method.equals("save")) {
                        return save(in, reply);
                    }
                case 6: 
                    if (method.equals("remove")) {
                        return remove(in, reply);
                    }
                case 11: 
                    if (method.equals("_get_handle")) {
                        return _get_handle(in, reply);
                    } else if (method.equals("isIdentical")) {
                        return isIdentical(in, reply);
                    }
                case 12: 
                    if (method.equals("_get_EJBHome")) {
                        return _get_EJBHome(in, reply);
                    }
                case 15: 
                    if (method.equals("_get_primaryKey")) {
                        return _get_primaryKey(in, reply);
                    }
                case 16: 
                    if (method.equals("armazenaAcidente")) {
                        return armazenaAcidente(in, reply);
                    }
            }
            throw new BAD_OPERATION();
        } catch (SystemException ex) {
            throw ex;
        } catch (Throwable ex) {
            throw new UnknownException(ex);
        }
    }
    
    private org.omg.CORBA.portable.OutputStream _get_EJBHome(org.omg.CORBA_2_3.portable.InputStream in , org.omg.CORBA.portable.ResponseHandler reply) throws Throwable {
        EJBHome result = target.getEJBHome();
        org.omg.CORBA.portable.OutputStream out = reply.createReply();
        Util.writeRemoteObject(out,result);
        return out;
    }
    
    private org.omg.CORBA.portable.OutputStream _get_primaryKey(org.omg.CORBA_2_3.portable.InputStream in , org.omg.CORBA.portable.ResponseHandler reply) throws Throwable {
        Object result = target.getPrimaryKey();
        org.omg.CORBA.portable.OutputStream out = reply.createReply();
        Util.writeAny(out,result);
        return out;
    }
    
    private org.omg.CORBA.portable.OutputStream remove(org.omg.CORBA_2_3.portable.InputStream in , org.omg.CORBA.portable.ResponseHandler reply) throws Throwable {
        try {
            target.remove();
        } catch (RemoveException ex) {
            String id = "IDL:javax/ejb/RemoveEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,RemoveException.class);
            return out;
        }
        org.omg.CORBA.portable.OutputStream out = reply.createReply();
        return out;
    }
    
    private org.omg.CORBA.portable.OutputStream _get_handle(org.omg.CORBA_2_3.portable.InputStream in , org.omg.CORBA.portable.ResponseHandler reply) throws Throwable {
        Handle result = target.getHandle();
        org.omg.CORBA.portable.OutputStream out = reply.createReply();
        Util.writeAbstractObject(out,result);
        return out;
    }
    
    private org.omg.CORBA.portable.OutputStream isIdentical(org.omg.CORBA_2_3.portable.InputStream in , org.omg.CORBA.portable.ResponseHandler reply) throws Throwable {
        EJBObject arg0 = (EJBObject) in.read_Object(EJBObject.class);
        boolean result = target.isIdentical(arg0);
        org.omg.CORBA.portable.OutputStream out = reply.createReply();
        out.write_boolean(result);
        return out;
    }
    
    private org.omg.CORBA.portable.OutputStream armazenaAcidente(org.omg.CORBA_2_3.portable.InputStream in , org.omg.CORBA.portable.ResponseHandler reply) throws Throwable {
        int arg0 = in.read_long();
        int arg1 = in.read_long();
        int arg2 = in.read_long();
        String arg3 = (String) in.read_value(String.class);
        String arg4 = (String) in.read_value(String.class);
        String arg5 = (String) in.read_value(String.class);
        String arg6 = (String) in.read_value(String.class);
        int arg7 = in.read_long();
        int arg8 = in.read_long();
        int arg9 = in.read_long();
        String arg10 = (String) in.read_value(String.class);
        int arg11 = in.read_long();
        String arg12 = (String) in.read_value(String.class);
        String arg13 = (String) in.read_value(String.class);
        String arg14 = (String) in.read_value(String.class);
        String arg15 = (String) in.read_value(String.class);
        int arg16 = in.read_long();
        String arg17 = (String) in.read_value(String.class);
        String arg18 = (String) in.read_value(String.class);
        int arg19 = in.read_long();
        String arg20 = (String) in.read_value(String.class);
        int arg21 = in.read_long();
        String arg22 = (String) in.read_value(String.class);
        String arg23 = (String) in.read_value(String.class);
        String arg24 = (String) in.read_value(String.class);
        String arg25 = (String) in.read_value(String.class);
        String arg26 = (String) in.read_value(String.class);
        int arg27 = in.read_long();
        int arg28 = in.read_long();
        int arg29 = in.read_long();
        String arg30 = (String) in.read_value(String.class);
        int arg31 = in.read_long();
        int arg32 = in.read_long();
        String arg33 = (String) in.read_value(String.class);
        String arg34 = (String) in.read_value(String.class);
        int arg35 = in.read_long();
        int arg36 = in.read_long();
        String arg37 = (String) in.read_value(String.class);
        int arg38 = in.read_long();
        String arg39 = (String) in.read_value(String.class);
        int arg40 = in.read_long();
        int arg41 = in.read_long();
        int[] arg42 = (int[]) in.read_value(int[].class);
        int arg43 = in.read_long();
        String arg44 = (String) in.read_value(String.class);
        String arg45 = (String) in.read_value(String.class);
        String arg46 = (String) in.read_value(String.class);
        String arg47 = (String) in.read_value(String.class);
        AuxTestemunha[] arg48 = (AuxTestemunha[]) in.read_value(AuxTestemunha[].class);
        int arg49 = in.read_long();
        String arg50 = (String) in.read_value(String.class);
        int arg51 = in.read_long();
        String arg52 = (String) in.read_value(String.class);
        String arg53 = (String) in.read_value(String.class);
        String arg54 = (String) in.read_value(String.class);
        String arg55 = (String) in.read_value(String.class);
        int arg56 = in.read_long();
        String arg57 = (String) in.read_value(String.class);
        int arg58 = in.read_long();
        String arg59 = (String) in.read_value(String.class);
        int arg60 = in.read_long();
        int arg61 = in.read_long();
        int arg62 = in.read_long();
        String arg63 = (String) in.read_value(String.class);
        String arg64 = (String) in.read_value(String.class);
        String arg65 = (String) in.read_value(String.class);
        String arg66 = (String) in.read_value(String.class);
        String result;
        try {
            result = target.armazenaAcidente(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21, arg22, arg23, arg24, arg25, arg26, arg27, arg28, arg29, arg30, arg31, arg32, arg33, arg34, arg35, arg36, arg37, arg38, arg39, arg40, arg41, arg42, arg43, arg44, arg45, arg46, arg47, arg48, arg49, arg50, arg51, arg52, arg53, arg54, arg55, arg56, arg57, arg58, arg59, arg60, arg61, arg62, arg63, arg64, arg65, arg66);
        } catch (Exception ex) {
            String id = "IDL:java/lang/Ex:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,Exception.class);
            return out;
        }
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value(result,String.class);
        return out;
    }
    
    private org.omg.CORBA.portable.OutputStream save(org.omg.CORBA_2_3.portable.InputStream in , org.omg.CORBA.portable.ResponseHandler reply) throws Throwable {
        try {
            target.save();
        } catch (Exception ex) {
            String id = "IDL:java/lang/Ex:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,Exception.class);
            return out;
        }
        org.omg.CORBA.portable.OutputStream out = reply.createReply();
        return out;
    }
}
