package br.smat.transaction.acidentetransaction;
import java.rmi.RemoteException;

import javax.ejb.CreateException;

import br.smat.objetosauxiliares.auxtestemunha.AuxTestemunha;
/**
 * Local interface for Enterprise Bean: AcidenteTransaction
 */
public interface AcidenteTransactionLocal extends javax.ejb.EJBLocalObject {
	public String armazenaAcidente(
		int acidente,
		int empresa,
		int emitente,
		String nome,
		String nomeResponsavel,
		String dataNascimento,
		String sexo,
		int estadoCivil,
		int ctps,
		int serie,
		String dataEmissaoCTPS,
		int ufCTPS,
		String remuneracaoMensal,
		String rg,
		String dataEmissaoRG,
		String orgaoExpedidorRG,
		int ufRG,
		String cpf,
		String pisPasepNit,
		int municipio,
		String rua,
		int numero,
		String bairro,
		String complemento,
		String cep,
		String ddd,
		String telefone,
		int vinculoEmpregaticio,
		int ocupacao,
		int area,
		String aposentado,
		int trabalhador,
		int empresaTerceira,
		String dataAcidente,
		String hora,
		int horasTrabalhadas,
		int tipoAcidente,
		String dataUltimodiaTrab,
		int tipoLocalAcidente,
		String descricaoLocal,
		int estadoAcidente,
		int municipioAcidente,
		int[] localLesaoAcidente,
		int agenteCausador,
		String descricaoSituacaoGeradora,
		String registroPolicial,
		String amputacao,
		String obito,
		AuxTestemunha[] vTestemunhas,
		int medico,
		String nomeMedico,
		int localAtendimento,
		String dataAtestado,
		String horaAtestado,
		String internacao,
		String afastamento,
		int duracaoTratamento,
		String descNaturezaLesao,
		int diagnostico,
		String observacoes,
		int crm,
		int ufCRM,
		int fonte,
		String numDocFonte,
		String dataEmissaoFonte,
		String distritoSaude,
		String descricaoDiagnostico) throws Exception;
	public void save() throws Exception;
}
