bcp smat..Estados out g:\batch\Estados.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Regionais out g:\batch\Regionais.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Municipios out g:\batch\Municipios.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..TiposLocalAcidente out g:\batch\TiposLocalAcidente.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Emitentes out g:\batch\Emitentes.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..TiposAcidente out g:\batch\TiposAcidente.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Areas out g:\batch\Areas.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Diagnosticos out g:\batch\Diagnosticos.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Fontes out g:\batch\Fontes.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..TiposEmpregadores out g:\batch\TiposEmpregadores.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..EstadosCivis out g:\batch\EstadosCivis.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Ocupacoes out g:\batch\Ocupacoes.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..VinculosEmpregaticios out g:\batch\VinculosEmpregaticios.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Periodicidades out g:\batch\periodicidades.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Locais out g:\batch\Locais.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Campos out g:\batch\Campos.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..TiposAgrupamento out g:\batch\TiposAgrupamento.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..TiposMedidasCorretivas out g:\batch\TiposMedidasCorretivas.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..GrausConformidade out g:\batch\GrausConformidade.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Status out g:\batch\Status.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go