bcp smat..Estados in g:\batch\Estados.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Regionais in g:\batch\Regionais.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Municipios in g:\batch\Municipios.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..TiposLocalAcidente in g:\batch\TiposLocalAcidente.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Emitentes in g:\batch\Emitentes.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..TiposAcidente in g:\batch\TiposAcidente.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Areas in g:\batch\Areas.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Diagnosticos in g:\batch\Diagnosticos.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Fontes in g:\batch\Fontes.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..TiposEmpregadores in g:\batch\TiposEmpregadores.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..EstadosCivis in g:\batch\EstadosCivis.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Ocupacoes in g:\batch\Ocupacoes.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..VinculosEmpregaticios in g:\batch\VinculosEmpregaticios.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Periodicidades in g:\batch\periodicidades.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Locais in g:\batch\Locais.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Campos in g:\batch\Campos.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..TiposAgrupamento in g:\batch\TiposAgrupamento.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..TiposMedidasCorretivas in g:\batch\TiposMedidasCorretivas.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..GrausConformidade in g:\batch\GrausConformidade.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
bcp smat..Status in g:\batch\Status.txt -SMAINFRAME -Usmat -Psmat -w -t|| -eg:\batch\error.txt go
